baseURL = 'https://rajp152k.github.io'
languageCode = 'en-us'
title = '(bit-mage)'
theme = "custom"

[Author]
  name = "(bit-mage)"
  bio = "(apply #'eval `((sudo ,explore ,exploit)))"

[Params]
  description = "thebitmage.com"
  head_logo = false
  copyright = "(Bit-Mage) - All rights reserved"
  schema = true
  toc = false
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "blog", "news", "docs"]
  comments = true
  search = true

[Params.sidebar]
  home = "left"   # Configure layout for home page
  list = "left"   # Configure layout for list pages
  single = "left" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["social", "taglist"]

[Params.widgets]
  recent_num = 20 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  github = "rajp152k"
  email = "raj@cognware.com"
  youtube = "@The-Bit-Mage"
  goodreads = "rajp152k"
  twitter = "@rajpatil152k"
  #instagram = "ln2.thebitmage"

[Params.style.vars]
  highlightColor = "#f7f9f9"

[Params.logo]
  image = "https://ik.imagekit.io/rajp152k/branding/Bit-Mage.png"
  title = "(Bit-Mage)"
  subtitle = "(apply #'eval `((sudo ,explore ,exploit)))"

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
[[menu.main]]
  identifier = 'now'
  name = 'now'
  pre = "<i class='fa fa-road'></i>"
  url = '/now/'
  weight = -109
[[menu.main]]
  identifier = 'scroll'
  name = 'scroll'
  pre = "<i class='fa fa-road'></i>"
  url = '/scroll/'
  weight = -108
# [[menu.main]]
#   name = 'notes'
#   pre = "<i class='fa fa-road'></i>"
#   url = 'https://buffer.thebitmage.com'
#   weight = -108
#[[menu.main]]
#  name = 'vlogs'
#  pre = "<i class='fa fa-road'></i>"
#  url = '/dd0x/'
#  weight = -105
[[menu.main]]
 name = 'work'
 pre = "<i class='fa fa-road'></i>"
 url = '/resume/'
#  weight = -102
# [[menu.main]]
#   identifier = 'all posts'
#   name = 'blogs'
#   pre = "<i class='fa fa-road'></i>"
#   url = '/all-posts/'
#   weight = -104
#[[menu.main]]
#  identifier = 'papershelf'
#  name = 'papershelf'
#  pre = "<i class='fa fa-road'></i>"
#  url = '/papershelf/'
#  weight = -104
#[[menu.main]]
#  identifier = 'docshelf'
#  name = 'docshelf'
#  pre = "<i class='fa fa-road'></i>"
#  url = '/docshelf/'
#  weight = -104
#[[menu.main]]
#  name = 'I know not..'
#  pre = "<i class='fa fa-road'></i>"
#  url = '/i-know-not/'
#  weight = -103
# [[menu.main]]
#   identifier = 'contact'
#   name = 'contact'
#   pre = "<i class='fa fa-road'></i>"
#   url = '/contact/'
#   weight = -102
